# Using as_strided from Numpy

In [4]:
import numpy as np

In [5]:
a=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(a)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [7]:
b=np.lib.stride_tricks.as_strided(a, (3,2,2,2), (24,8,24,8))
print(b.shape)
print(b)

(3, 2, 2, 2)
[[[[ 1.  2.]
   [ 4.  5.]]

  [[ 2.  3.]
   [ 5.  6.]]]


 [[[ 4.  5.]
   [ 7.  8.]]

  [[ 5.  6.]
   [ 8.  9.]]]


 [[[ 7.  8.]
   [10. 11.]]

  [[ 8.  9.]
   [11. 12.]]]]


In [8]:
b=b.reshape(6,4)
print(b)

[[ 1.  2.  4.  5.]
 [ 2.  3.  5.  6.]
 [ 4.  5.  7.  8.]
 [ 5.  6.  8.  9.]
 [ 7.  8. 10. 11.]
 [ 8.  9. 11. 12.]]


 # Using view_as_windows from skimage

In [10]:
from skimage.util.shape import view_as_windows
b = view_as_windows(a, (2,2))
print(b.shape)
print(b)

(3, 2, 2, 2)
[[[[ 1.  2.]
   [ 4.  5.]]

  [[ 2.  3.]
   [ 5.  6.]]]


 [[[ 4.  5.]
   [ 7.  8.]]

  [[ 5.  6.]
   [ 8.  9.]]]


 [[[ 7.  8.]
   [10. 11.]]

  [[ 8.  9.]
   [11. 12.]]]]


In [11]:
b = b.reshape(6,4)
print(b)

[[ 1.  2.  4.  5.]
 [ 2.  3.  5.  6.]
 [ 4.  5.  7.  8.]
 [ 5.  6.  8.  9.]
 [ 7.  8. 10. 11.]
 [ 8.  9. 11. 12.]]


# Test for final implementation

In [10]:
from ConvLayer import ConvLayer
b = ConvLayer._im2col(a, (2,2))
print(b)

[[ 1.  2.  4.  5.]
 [ 2.  3.  5.  6.]
 [ 4.  5.  7.  8.]
 [ 5.  6.  8.  9.]
 [ 7.  8. 10. 11.]
 [ 8.  9. 11. 12.]]
