# Creating MaxPool mask and activations

In [51]:
import numpy as np
import random

In [52]:
# create randomised input
r,c = 4,9 # size of input
x = list(range(r*c))
random.shuffle(x)
x = np.reshape(x, (r,c))
print(x)
print(x.shape)

[[ 2 22 35 14 28 15 21  4  8]
 [ 9 24 23 26  6  0 16 12  3]
 [ 7 17 31 30 11 34 29  1 10]
 [13 25 27  5 32 19 33 18 20]]
(4, 9)


In [53]:
# calculate activations size
pr,pc = 2,3 # pool size
assert r % pr == 0
assert c % pc == 0
ar,ac = r // pr, c // pc 

In [54]:
# transform input into pools
a = np.transpose(np.reshape(x, (ar,pr,ac,pc)), (0,2,1,3)) 
print(a)
print(a.shape)

[[[[ 2 22 35]
   [ 9 24 23]]

  [[14 28 15]
   [26  6  0]]

  [[21  4  8]
   [16 12  3]]]


 [[[ 7 17 31]
   [13 25 27]]

  [[30 11 34]
   [ 5 32 19]]

  [[29  1 10]
   [33 18 20]]]]
(2, 3, 2, 3)


In [55]:
# flatten pools
a = np.reshape(a, (ar,ac,-1))
print(a)
print(a.shape)

[[[ 2 22 35  9 24 23]
  [14 28 15 26  6  0]
  [21  4  8 16 12  3]]

 [[ 7 17 31 13 25 27]
  [30 11 34  5 32 19]
  [29  1 10 33 18 20]]]
(2, 3, 6)


In [56]:
# get indexes of maximum values
i = np.argmax(a, 2)
print(i)
print(i.shape)

[[2 1 0]
 [2 2 3]]
(2, 3)


In [57]:
# create mask for maximum values
m = i[:,:,None] == range(a.shape[-1])
print(m)
print(m.shape)

[[[False False  True False False False]
  [False  True False False False False]
  [ True False False False False False]]

 [[False False  True False False False]
  [False False  True False False False]
  [False False False  True False False]]]
(2, 3, 6)


In [58]:
# apply mask to flattened pools
a *= m
print(a)
print(a.shape)

[[[ 0  0 35  0  0  0]
  [ 0 28  0  0  0  0]
  [21  0  0  0  0  0]]

 [[ 0  0 31  0  0  0]
  [ 0  0 34  0  0  0]
  [ 0  0  0 33  0  0]]]
(2, 3, 6)


In [59]:
# sum pool values to get final activation
a = np.sum(a, 2)
print(a)
print(a.shape)

[[35 28 21]
 [31 34 33]]
(2, 3)


# Backpropagation

In [65]:
# repeat max values within each pool
b = np.repeat(a, pr, 0)
b = np.repeat(b, pc, 1)
print(b)
print(b.shape)

[[35 35 35 28 28 28 21 21 21]
 [35 35 35 28 28 28 21 21 21]
 [31 31 31 34 34 34 33 33 33]
 [31 31 31 34 34 34 33 33 33]]
(4, 9)


In [66]:
# transform into flattened pools
b = np.transpose(np.reshape(b, (ar,pr,ac,pc)), (0,2,1,3)) 
b = np.reshape(b, (ar,ac,-1))
print(b)
print(b.shape)

[[[35 35 35 35 35 35]
  [28 28 28 28 28 28]
  [21 21 21 21 21 21]]

 [[31 31 31 31 31 31]
  [34 34 34 34 34 34]
  [33 33 33 33 33 33]]]
(2, 3, 6)


In [67]:
# apply mask
b *= m
print(b)
print(b.shape)

[[[ 0  0 35  0  0  0]
  [ 0 28  0  0  0  0]
  [21  0  0  0  0  0]]

 [[ 0  0 31  0  0  0]
  [ 0  0 34  0  0  0]
  [ 0  0  0 33  0  0]]]
(2, 3, 6)
